url: https://openplanetary.github.io
baseurl:

# Site settings
title: OpenPlanetary
email: openplanetary@gmail.com
description: "Join the growing community of planetary scientists and mappers using open source GIS technologies to expand our understanding of the planets."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6698C8 #b8b8b8 #ef880f #fed136
  secondary: b8b8b8 #F2B46B #fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name:
  pic:
  position:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name:
  pic:
  position:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name:
  pic:
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/openplanetary
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/planetary
  - title: github
    url: http://github.com/openplanetary
#  - title: google
#    url: http://plus.google.com/openplanetary

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty