url: https://nmanaud.github.io
baseurl: /whereonmars

# Site settings
title: Where On Mars?
email: nmanaud@gmail.com
description: "Interactive web map visualization of the ESA's ExoMars Rover candidates landing sites"

# Color settings (hex-codes without the leading hash-tag) fed136, fec503
color:
  # primary: fec503
  # secondary: fed136


  primary: EFAF3D
  secondary: EFC481

  secondary-dark: 341a13

# Team names, titles and social links
people:
- name: Nicolas Manaud
  pic: 1
  position: Project Initiator
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #

- name: Oriol Boix
  pic: 2
  position: Front-End Developer Intern
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #

- name: Andrew Hill
  pic: 3
  position: CartoDB Support
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #

# - name: Elliot Sefton-Nash
#   pic: 4
#   position: Planetary Scientist at UCL/London
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #
#
# - name: Carla Iriberri
#   pic: 5
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #
#
# - name: Daniel Carrión
#   pic: 6
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/whereonmars
  - title: facebook
    url: https://www.facebook.com/whereonmars
  - title: github
    url: http://nmanaud.github.com/whereonmars

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-65388785-1'
