// define object that have all the elements and layers
var el = {
  map: null,
  basemap: null,
  basemap2: null,
  basemapShadedColor: null,
  basemapCelestia: null,
  basemapNoShadedColor:null,
  torqueLayer: null,
  torqueEllipses1: null,
  torqueEllipses2: null,
  story: null,
  hirise: null,
  hrsc: null,
  Aram: null,
  Hypanis:null,
  Oxia: null,
  Mawrth: null,
  center: null,
  landingSite: null,
  landingSite8: null,
  latConstraint: null,
  elevationConstraint:null,
  geoConstraint: null,
  duneConstraint: null,
  geoOkConstraint: null,
  geoNoOkContraint: null,
  nomenclator: null,
  ellipses1: null,
  ellipses2: null,
  ellipses3: null,
  ellipses4: null,
  ellipses5: null,
  ellipses6: null,
  ellipses7: null,
  ellipses8: null,
  dashellipses1: null,
  dashellipses2: null,
  dashellipses3: null,
  dashellipses4: null,
  dashellipses5: null,
  dashellipses6: null,
  dashellipses7: null,
  dashellipses8: null,
  LayerActions: null
};
